defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: tis_project_development

test:
  <<: *defaults
  database: tis_project_test

# set these environment variables on your prod server
#production:
#  <<: *defaults
#  database: tis_project
#  username: <%= ENV['MONGO_USERNAME'] %>
#  password: <%= ENV['MONGO_PASSWORD'] %>
#   uri: <%= ENV['MONGODB_URI'] %>

production:
  <<: *defaults
  host: ds031637.mongolab.com
  port:31637
  username: administrador
  password: administrador
  database: heroku_app8600246